### ISSUE TITLE
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

### ISSUE THREAD

**Issue by chaotianjiao** [akshaybahadur21/Drowsiness_Detection#10]
Hello~It's a nice repo and I like it very much!
when I run Drowsiness_Detection.py  I got nothing but:
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
then python breaked and let me report the error.
How can I solve this problem?

**Comment by akshaybahadur21** [comment]
@chaotianjiao - It's a memory issue error.
Kindly refer to Stackoverflow and debug.
