### ISSUE TITLE
Minute error

### ISSUE THREAD

**Issue by Diksha0625** [akshaybahadur21/Drowsiness_Detection#12]
You should change cap.stop() to cap.release() in the last line as cv2 doesn't support stop().

**Comment by muhammedsinan** [comment]
File "C:\Users\msina\Desktop\Drowsiness_Detection-master\Drowsiness_Detection.py", line 1, in <module>
    from scipy.spatial import distance
ModuleNotFoundError: No module named 'scipy'


how  to resolve

**Comment by akshaybahadur21** [comment]
@Diksha0625  - Thanks for pointing it out.
Made the changes.

**Comment by akshaybahadur21** [comment]
@muhammedsinan - you need to install scipy
