### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by Nit72003** [akshaybahadur21/Drowsiness_Detection#17]
Hello,
When i try running it with everything installed, it is giving me a runtime error unable to open ".\shape_predicctor_68_face_landmarks.dat"

**Comment by tuna-date** [comment]
@Nit72003 Try remove the backslash in the path
`dlib.shape_predictor('shape_predictor_68_face_landmarks.dat') `

**Comment by akshaybahadur21** [comment]
Resolved
