### ISSUE TITLE
face_utils.FACIAL_LANDMARKS_IDXS does not exist

### ISSUE THREAD

**Issue by ionicc** [akshaybahadur21/Drowsiness_Detection#3]
For new deployments of imutils, face_utils.FACIAL_LANDMARKS_IDXS has been updated with:
- face_utils.FACIAL_LANDMARKS_68_IDXS

The project does not work with the new deployments. If you approve then I'll put up a PR to change it.

**Comment by jajoe** [comment]
I have the same issue. Please tell me when you know how to fix it. Maybe we could use FACIAL_LANDMARKS_IDXS from the module .helpers used here : 
https://www.pyimagesearch.com/2017/05/22/face-alignment-with-opencv-and-python/

**Comment by ionicc** [comment]
Alright, I have updated my fork with the fix and it works now. I'll close this issue now 😄 
https://github.com/ionicc/Drowsiness_Detection
