### ISSUE TITLE
alaram alert

### ISSUE THREAD

**Issue by girikumarkolla** [akshaybahadur21/Drowsiness_Detection#9]
hai
I want to add a sound alert when eye closes can you say how to add I am trying not working please help me

**Comment by vinayakpahalwan7** [comment]
> hai
> I want to add a sound alert when eye closes can you say how to add I am trying not working please help me

 @girikumarkolla You can use `playsound` library and create a function that plays the audio file `playsound.playsound(path)` 
Now, after this line, `if flag >= frame_check:` you can start a thread to play an alarm sound in the background (if the eyes were closed for a sufficient threshold number).

**Comment by samardhiman007** [comment]
@vinayakpahalwan7 can you please help me in adding an alert to this project. I am trying to do this for the last 3 weeks but I am not able to do so please help me out.

**Comment by akshaybahadur21** [comment]
This might be helpful for adding sound alerts.
https://stackoverflow.com/questions/16573051/sound-alarm-when-code-finishes

**Comment by akshaybahadur21** [comment]
Closing the issue.
Thanks
